### ISSUE TITLE
Change in CSS styling

### ISSUE THREAD

**Issue by Dishant145** [sruthisagar/Wizards-Of-Web#4]
@sruthisagar Hi! 
I am participating in Hacktoberfest 2021 !

I have made some changes in CSS styling. I have made the pull request. So can you review it and accept it if everything is fine.

Thanks!

**Comment by sruthisagar** [comment]
> @sruthisagar Hi! I am participating in Hacktoberfest 2021 !
> 
> I have made some changes in CSS styling. I have made the pull request. So can you review it and accept it if everything is fine.
> 
> Thanks!

Hi @Dishant145 😁

It looks like you've given the link to the CSS file as "g.css" in index.html. But the actual CSS file name is still "style.css". So the CSS file is not linked to the HTML file. Can you just correct the linking part in index.html?

**Comment by Dishant145** [comment]
Yes sorry about that, I will make correct that:)

**Comment by Dishant145** [comment]
I have made the changes. If you feel the contribution is not upto the mark for Hacktoberfest, I will definitely make more changes. 
Please do tell.
Thank you!

**Comment by sruthisagar** [comment]
This looks pretty good! But the cat pics seem to be shrunk width wise. Can you try taking off the width properties of card and card img, and changing the height property of card to maybe 250px? Or if you've got a better way to fix it, feel free to do it 😌

**Comment by Dishant145** [comment]
Yeah, I will do as you intend.
